version: "2"


services:



  prometheus:
    image: 192.168.7.61/library/prometheus:3.12
    ports:
      - "9091:9090"
    env_file:
      - commons.env
    volumes:
      - /home/ubuntu/prometheus:/prometheus
      - /home/ubuntu/moniting/:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=14d'

  grafana:
    image: 192.168.7.61/library/grafana:7.2.0
    ports:
      - "3000:3000"
    env_file:
      - commons.env
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD__FILE=/home/ubuntu/moniting/GF_SECURITY_ADMIN_PASSWORD
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_AUTH_ANONYMOUS_ENABLED=false
    volumes:
      - /home/ubuntu/grafana:/var/lib/grafana

  mgmt-mysqlexporter:
    image: prom/mysqld-exporter:v0.12.1
    ports:
      - "9104:9104"
    environment:
      #your mysql address "<user>:<pwd>@(<mysql ip>:<port>)/"
      - DATA_SOURCE_NAME="root:admin789@(192.168.6.225:3306)/"
      
  mgmt-nginxexporter:
      image: sophos/nginx-vts-exporter
      ports:
        - "9913:9913"
      environment:
        #your nginx address
        - NGINX_STATUS=http://192.168.7.111/status/format/json
        
  mgmt-mssqlexporter:
      image: awaragi/prometheus-mssql-exporter
      ports:
        - "4000:4000"
      environment:
        #your sqlserver ip
        - SERVER=192.168.7.37
        #your sqlserver user
        - USERNAME=sop
        #your sqlserver password
        - PASSWORD=password$$1
        - DEBUG=app

